### ISSUE TITLE
Publications à Dockerhub

### ISSUE THREAD

**Issue by NicolasBeaulieu88** [NicolasBeaulieu88/oxygencs-grp2-eq2#6]
**Is your feature request related to a problem? Please describe.**
On doit publier sur le Dockerhub les images lorsqu'elles sont créées.

**Describe the solution you'd like**
à voir

**Describe alternatives you've considered**
aucune autre

**Additional context**
voir énoncé du lab

**Comment by SantiagoChiappe** [comment]
Les repos sur Docker Hub sont : 
- santiagochiappe/log680_metrics
- santiagochiappe/log680_oxygencs
